void __fastcall std::exception::~exception(std::exception *this)
{
  ;
}
